sudo: required

language: python

services:
  - docker

before_install:
- docker pull elgalu/selenium:latest
- docker run -d --name=grid -p 127.0.0.1:4444:24444 -v /dev/shm:/dev/shm elgalu/selenium:latest
- docker images
- docker ps -a

install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt

script:
- python hola.py

after_script:
- docker stop grid
- docker rm grid
