sudo: required

language: python
python:
  - "2.7"

services:
  - docker

env:
  - SEL_IMG_TAG=latest

before_install:
- docker pull elgalu/selenium:${SEL_IMG_TAG}
- docker run -d --name=grid -p 4444:24444 -v /dev/shm:/dev/shm elgalu/selenium:${SEL_IMG_TAG}
- docker images
- docker ps -a

install:
- pip install --upgrade -r requirements.txt

script:
- python hola.py

after_script:
- docker stop grid
- docker rm grid
